force-app/main/default/objects/Plant__c/fields/Last_Watered__c.field-meta.xml
<CustomField>
    <fullName>Last_Watered__c</fullName>
    <label>Last Watered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Specie__c.field-meta.xml
<CustomField>
    <fullName>Specie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specie</label>
    <referenceTo>Specie__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specie__c/Specie__c.object-meta.xml
<CustomObject>
    <label>Specie</label>
    <nameField>
        <label>Specie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PlantTriggerTest.cls
@isTest
public with sharing class PlantTriggerTest {
    @isTest
    static void insertPlant_lastWateredSetup_nextWateringDateCalculatedCorretly(){

        Specie__c orquidea = new Specie__c();
        orquidea.Summer_Watering_Frequency__c = 'Weekly';
        insert orquidea;

        Plant__c plant1 = new Plant__c();
        plant1.Last_Fertilized__c = System.today();
        plant1.Last_Watered__c = System.today();
        plant1.Specie__c = orquidea.Id;

        insert plant1;

        plant1 = [SELECT Next_Water__c FROM Plant__c WHERE Id = :plant1.Id];
        System.assertEquals(System.today() + 7, plant1.Next_Water__c);
    }
}